INFO:root:worker id set to 0
INFO:root:Running task 0 in worker 0
INFO:root:cached is dict_keys([])
INFO:root:Running task 0 in worker 0
INFO:root:cached is dict_keys([])
INFO:root:-- Task 0 successfully finished --
ERROR:root:Task 0 returned an error while updating status: Traceback (most recent call last):
  File "/home/seth/projects/fed-learn-experiment/swarm/dist_swarm/ovm_utils/task_runner.py", line 102, in run_task
    worker_in_db.update_finished_task(task_id, True, measured_time)
  File "../dist_swarm/db_bridge/worker_in_db.py", line 70, in update_finished_task
    Item={TASK_ID: task_id, IS_FINISHED: is_finished, IS_PROCESSED: False, TIME: measured_time}
  File "/home/seth/projects/fed-learn-experiment/venv/lib/python3.6/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/seth/projects/fed-learn-experiment/venv/lib/python3.6/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/seth/projects/fed-learn-experiment/venv/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/seth/projects/fed-learn-experiment/venv/lib/python3.6/site-packages/botocore/client.py", line 649, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/home/seth/projects/fed-learn-experiment/venv/lib/python3.6/site-packages/botocore/client.py", line 695, in _convert_to_request_dict
    api_params, operation_model, context)
  File "/home/seth/projects/fed-learn-experiment/venv/lib/python3.6/site-packages/botocore/client.py", line 727, in _emit_api_params
    params=api_params, model=operation_model, context=context)
  File "/home/seth/projects/fed-learn-experiment/venv/lib/python3.6/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/seth/projects/fed-learn-experiment/venv/lib/python3.6/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/home/seth/projects/fed-learn-experiment/venv/lib/python3.6/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/home/seth/projects/fed-learn-experiment/venv/lib/python3.6/site-packages/boto3/dynamodb/transform.py", line 197, in inject_attribute_value_input
    'AttributeValue')
  File "/home/seth/projects/fed-learn-experiment/venv/lib/python3.6/site-packages/boto3/dynamodb/transform.py", line 254, in transform
    model, params, transformation, target_shape)
  File "/home/seth/projects/fed-learn-experiment/venv/lib/python3.6/site-packages/boto3/dynamodb/transform.py", line 261, in _transform_parameters
    model, params, transformation, target_shape)
  File "/home/seth/projects/fed-learn-experiment/venv/lib/python3.6/site-packages/boto3/dynamodb/transform.py", line 276, in _transform_structure
    target_shape)
  File "/home/seth/projects/fed-learn-experiment/venv/lib/python3.6/site-packages/boto3/dynamodb/transform.py", line 261, in _transform_parameters
    model, params, transformation, target_shape)
  File "/home/seth/projects/fed-learn-experiment/venv/lib/python3.6/site-packages/boto3/dynamodb/transform.py", line 285, in _transform_map
    params[key] = transformation(value)
  File "/home/seth/projects/fed-learn-experiment/venv/lib/python3.6/site-packages/boto3/dynamodb/types.py", line 102, in serialize
    dynamodb_type = self._get_dynamodb_type(value)
  File "/home/seth/projects/fed-learn-experiment/venv/lib/python3.6/site-packages/boto3/dynamodb/types.py", line 115, in _get_dynamodb_type
    elif self._is_number(value):
  File "/home/seth/projects/fed-learn-experiment/venv/lib/python3.6/site-packages/boto3/dynamodb/types.py", line 160, in _is_number
    'Float types are not supported. Use Decimal types instead.')
TypeError: Float types are not supported. Use Decimal types instead.

INFO:root:worker id set to 0
INFO:root:Running task 0 in worker 0
INFO:root:cached is dict_keys([])
INFO:root:-- Task 0 successfully finished --
INFO:root:Running task 0 in worker 0
INFO:root:cached is dict_keys(['0'])
INFO:root:device state 0 loaded from cache
INFO:root:-- Task 0 successfully finished --
INFO:root:worker id set to 0
INFO:root:Running task 0 in worker 0
INFO:root:cached is dict_keys([])
INFO:root:-- Task 0 successfully finished --
INFO:root:Running task 0 in worker 0
INFO:root:cached is dict_keys(['0'])
INFO:root:device state 0 loaded from cache
INFO:root:-- Task 0 successfully finished --
INFO:root:Running task 0 in worker 0
INFO:root:cached is dict_keys(['0'])
INFO:root:device state 0 loaded from cache
INFO:root:-- Task 0 successfully finished --
INFO:root:Running task 0 in worker 0
INFO:root:cached is dict_keys(['0'])
INFO:root:device state 0 loaded from cache
INFO:root:-- Task 0 successfully finished --
2022-12-24 06:59:39,906,906 root ERROR Traceback (most recent call last):
  File "/home/seth/projects/fed-learn-experiment/swarm/dist_swarm/simulate_device.py", line 46, in RunTask
    run_task_thread = threading.Thread(target=run_task, args=(self.worker_status, self.worker_id, config, self.cache))
AttributeError: 'SimulateDeviceServicer' object has no attribute 'worker_status'

2022-12-24 06:59:39,906,906 grpc._server ERROR Exception calling application: 'SimulateDeviceServicer' object has no attribute 'worker_status'
Traceback (most recent call last):
  File "/home/seth/projects/fed-learn-experiment/swarm/dist_swarm/simulate_device.py", line 46, in RunTask
    run_task_thread = threading.Thread(target=run_task, args=(self.worker_status, self.worker_id, config, self.cache))
AttributeError: 'SimulateDeviceServicer' object has no attribute 'worker_status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/seth/projects/fed-learn-experiment/venv/lib/python3.6/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/home/seth/projects/fed-learn-experiment/swarm/dist_swarm/simulate_device.py", line 52, in RunTask
    return Status(status=self.worker_status)
AttributeError: 'SimulateDeviceServicer' object has no attribute 'worker_status'
2022-12-24 07:00:16,825,825 grpc._server ERROR Exception calling application: __init__() missing 1 required positional argument: 'worker_id'
Traceback (most recent call last):
  File "/home/seth/projects/fed-learn-experiment/venv/lib/python3.6/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/home/seth/projects/fed-learn-experiment/swarm/dist_swarm/simulate_device.py", line 37, in SetWorkerInfo
    self.worker_in_db = WorkerInDB(request.swarm_name, request.worker_id)
TypeError: __init__() missing 1 required positional argument: 'worker_id'
2022-12-24 07:01:33,748,748 grpc._server ERROR Exception calling application: __init__() missing 1 required positional argument: 'worker_id'
Traceback (most recent call last):
  File "/home/seth/projects/fed-learn-experiment/venv/lib/python3.6/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/home/seth/projects/fed-learn-experiment/swarm/dist_swarm/simulate_device.py", line 37, in SetWorkerInfo
    self.worker_in_db = WorkerInDB(request.swarm_name, request.worker_id)
TypeError: __init__() missing 1 required positional argument: 'worker_id'
2022-12-24 07:03:33,785,785 grpc._server ERROR Exception calling application: __init__() missing 1 required positional argument: 'worker_id'
Traceback (most recent call last):
  File "/home/seth/projects/fed-learn-experiment/venv/lib/python3.6/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/home/seth/projects/fed-learn-experiment/swarm/dist_swarm/simulate_device.py", line 37, in SetWorkerInfo
    self.worker_in_db = WorkerInDB(request.swarm_name, request.worker_id)
TypeError: __init__() missing 1 required positional argument: 'worker_id'
2022-12-24 08:03:38,574,574 grpc._server ERROR Exception calling application: An error occurred (ResourceNotFoundException) when calling the Query operation: Requested resource not found
Traceback (most recent call last):
  File "/home/seth/projects/fed-learn-experiment/venv/lib/python3.6/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/home/seth/projects/fed-learn-experiment/swarm/dist_swarm/simulate_device.py", line 37, in SetWorkerInfo
    self.worker_in_db = WorkerInDB(request.swarm_name, request.worker_namespace, request.worker_id)
  File "../dist_swarm/db_bridge/worker_in_db.py", line 15, in __init__
    self.fetch_status()
  File "../dist_swarm/db_bridge/worker_in_db.py", line 22, in fetch_status
    KeyConditionExpression=Key(WORKER_ID).eq(self.worker_id))
  File "/home/seth/projects/fed-learn-experiment/venv/lib/python3.6/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/seth/projects/fed-learn-experiment/venv/lib/python3.6/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/seth/projects/fed-learn-experiment/venv/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/seth/projects/fed-learn-experiment/venv/lib/python3.6/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Query operation: Requested resource not found
2022-12-24 08:04:42,313,313 root INFO worker id set to 0
2022-12-24 08:05:08,195,195 root INFO Running task 0 in worker 0
2022-12-24 08:05:08,195,195 root INFO cached is dict_keys([])
2022-12-24 08:59:18,553,553 root INFO worker id set to 0
2022-12-24 08:59:24,309,309 root INFO Running task 0 in worker 0
2022-12-24 08:59:24,309,309 root INFO cached is dict_keys([])
2022-12-24 09:02:40,430,430 root INFO worker id set to 0
2022-12-24 09:02:42,797,797 root INFO Running task 0 in worker 0
2022-12-24 09:02:42,797,797 root INFO cached is dict_keys([])
2022-12-24 09:03:46,750,750 root INFO worker id set to 0
2022-12-24 09:03:48,419,419 root INFO Running task 0 in worker 0
2022-12-24 09:03:48,420,420 root INFO cached is dict_keys([])
2022-12-24 09:04:27,749,749 root INFO -- Task 0 successfully finished --
2022-12-26 06:25:05,499,499 root INFO worker id set to 0
2022-12-26 06:25:14,672,672 root INFO Running task 0 in worker 0
2022-12-26 06:25:14,672,672 root INFO cached is dict_keys([])
2022-12-26 06:25:55,297,297 root INFO Running task 0 in worker 0
2022-12-26 06:25:55,297,297 root INFO cached is dict_keys([])
2022-12-26 06:30:03,135,135 root INFO worker id set to 0
2022-12-26 06:30:04,740,740 root INFO Running task 0 in worker 0
2022-12-26 06:30:04,740,740 root INFO cached is dict_keys([])
2022-12-26 18:12:14,821,821 grpc._server ERROR Exception calling application: An error occurred (ResourceNotFoundException) when calling the Query operation: Requested resource not found
Traceback (most recent call last):
  File "/home/seth/projects/fed-learn-experiment/venv/lib/python3.6/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/home/seth/projects/fed-learn-experiment/swarm/dist_swarm/simulate_device.py", line 37, in SetWorkerInfo
    self.worker_in_db = WorkerInDB(request.swarm_name, request.worker_namespace, request.worker_id)
  File "../dist_swarm/db_bridge/worker_in_db.py", line 15, in __init__
    self.fetch_status()
  File "../dist_swarm/db_bridge/worker_in_db.py", line 22, in fetch_status
    KeyConditionExpression=Key(WORKER_ID).eq(self.worker_id))
  File "/home/seth/projects/fed-learn-experiment/venv/lib/python3.6/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/seth/projects/fed-learn-experiment/venv/lib/python3.6/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/seth/projects/fed-learn-experiment/venv/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/seth/projects/fed-learn-experiment/venv/lib/python3.6/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Query operation: Requested resource not found
2022-12-26 18:12:54,734,734 root INFO worker id set to 0
2022-12-26 18:12:59,518,518 root INFO Running task 0 in worker 0
2022-12-26 18:12:59,519,519 root INFO cached is dict_keys([])
2022-12-26 18:13:47,315,315 root INFO -- Task 0 successfully finished --
2023-01-02 06:14:35,568,568 root INFO worker id set to 0
2023-01-02 06:14:35,568,568 grpc._server ERROR Exception calling application: 'SimulateDeviceServicer' object has no attribute 'worker_status'
Traceback (most recent call last):
  File "/home/seth/projects/fed-learn-experiment/venv/lib/python3.6/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/home/seth/projects/fed-learn-experiment/swarm/dist_swarm/simulate_device.py", line 46, in SetWorkerInfo
    return Status(status=self.worker_status)
AttributeError: 'SimulateDeviceServicer' object has no attribute 'worker_status'
2023-01-02 06:14:52,395,395 root INFO worker id set to 0
2023-01-02 06:14:52,395,395 grpc._server ERROR Exception calling application: 'SimulateDeviceServicer' object has no attribute 'worker_status'
Traceback (most recent call last):
  File "/home/seth/projects/fed-learn-experiment/venv/lib/python3.6/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/home/seth/projects/fed-learn-experiment/swarm/dist_swarm/simulate_device.py", line 46, in SetWorkerInfo
    return Status(status=self.worker_status)
AttributeError: 'SimulateDeviceServicer' object has no attribute 'worker_status'
2023-01-02 06:15:16,790,790 root INFO worker id set to 0
2023-01-02 06:15:16,790,790 grpc._server ERROR Exception calling application: 'SimulateDeviceServicer' object has no attribute 'worker_status'
Traceback (most recent call last):
  File "/home/seth/projects/fed-learn-experiment/venv/lib/python3.6/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/home/seth/projects/fed-learn-experiment/swarm/dist_swarm/simulate_device.py", line 46, in SetWorkerInfo
    return Status(status=self.worker_status)
AttributeError: 'SimulateDeviceServicer' object has no attribute 'worker_status'
2023-01-02 06:23:36,684,684 root INFO worker id set to 0
2023-01-02 06:23:58,697,697 root INFO Running task 0 in worker 0
2023-01-02 06:23:58,697,697 root INFO cached is dict_keys([])
2023-01-02 06:24:35,546,546 root INFO -- Task 0 successfully finished --
2023-01-02 09:32:49,692,692 root INFO worker id set to 0
2023-01-02 09:33:01,794,794 root INFO Running task 0 in worker 0
2023-01-02 09:33:01,794,794 root INFO cached is dict_keys([])
2023-01-02 09:33:47,250,250 root INFO -- Task 0 successfully finished --
2023-01-02 09:33:47,441,441 root ERROR Traceback (most recent call last):
  File "../dist_swarm/db_bridge/rds_bridge.py", line 29, in execute_sql
    self.cursor.execute(query)
psycopg2.errors.UndefinedTable: relation "ovm_example_finished_tasks" does not exist
LINE 1: INSERT INTO ovm_example_finished_tasks (task_id, is_processe...
                    ^


2023-01-02 09:35:17,313,313 root INFO Running task 0 in worker 0
2023-01-02 09:35:17,313,313 root INFO cached is dict_keys(['0'])
2023-01-02 09:35:17,313,313 root INFO device state 0 loaded from cache
2023-01-02 09:35:51,988,988 root INFO -- Task 0 successfully finished --
2023-01-02 09:36:32,557,557 root INFO Running task 0 in worker 0
2023-01-02 09:36:32,557,557 root INFO cached is dict_keys(['0'])
2023-01-02 09:36:32,557,557 root INFO device state 0 loaded from cache
2023-01-02 09:37:04,500,500 root INFO -- Task 0 successfully finished --
2023-01-07 18:34:31,780,780 root INFO worker id set to 0
2023-01-07 18:34:39,785,785 root INFO Running task 99999 in worker 0
2023-01-07 18:34:39,786,786 root INFO cached is dict_keys([])
2023-01-07 18:35:39,619,619 root INFO -- Task 99999 successfully finished --
2023-01-07 18:40:39,040,40 root INFO worker id set to 0
2023-01-07 18:40:40,603,603 root INFO Running task 99999 in worker 0
2023-01-07 18:40:40,603,603 root INFO cached is dict_keys([])
2023-01-07 18:44:28,136,136 root INFO worker id set to 0
2023-01-07 18:44:38,175,175 root INFO Running task 99999 in worker 0
2023-01-07 18:44:38,175,175 root INFO cached is dict_keys([])
2023-01-07 18:45:38,449,449 root INFO -- Task 99999 successfully finished --
2023-01-07 18:54:15,730,730 root INFO Running task 99999 in worker 0
2023-01-07 18:54:15,731,731 root INFO cached is dict_keys(['0'])
2023-01-07 18:54:15,731,731 root INFO device state 0 loaded from cache
2023-01-07 18:54:56,785,785 root INFO -- Task 99999 successfully finished --
